version: '3.6'

services:
  db:
    image: postgres:10-alpine    
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ~/postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: 
      redis-server 
    # volumes: 
    #  - cache:/data