version: '3.6'

services:
  db:
    image: postgres:10-alpine    
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ~/postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - ${REDIS_DOCKER_PORT}:6379
    command: 
      redis-server 
    # volumes: 
    #  - cache:/data
  grafana:
    image: grafana/grafana:8.1.2
    #network_mode: default
    ports:
      - ${GRAFANA_DOCKER_COMPOSE_PORT}:3000
    volumes:
      - ./docker/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml 
      - grafana-data:/var/lib/grafana/
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo
      #- prometheus
  tempo:
    image: grafana/tempo:1.1.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - ${TEMPO_DOCKER_COMPOSE_PORT}:8000 # tempo
      - 55681:55681 # otlp http
  gameplatform:
    image: gameplatform
    environment: 
      DATABASE_URL: "postgres://postgres:postgres@db/gameplatform_dev"
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      GRAFANA_TOKEN: ${GRAFANA_TOKEN}
      AUTH_KEY: ${AUTH_KEY}
      MESSAGING_SERVICE_SID: ${MESSAGING_SERVICE_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_HOST: redis
      REDIS_DOCKER_PORT: ${REDIS_DOCKER_PORT}
    depends_on:
      - db
      - redis
    links: 
      - db
      - redis
    ports: 
      - "4000:4000"
volumes:
  grafana-data: {}