version: '3.6'

services:
  db:
    image: postgres:10-alpine    
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ~/postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: 
      redis-server 
    # volumes: 
    #  - cache:/data
  grafana:
    image: grafana/grafana:8.1.2
    #network_mode: default
    ports:
      - ${GRAFANA_DOCKER_COMPOSE_PORT}:3000
    volumes:
      - ./docker/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml 
      - grafana-data:/var/lib/grafana/
    environment:
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo
      #- prometheus
  loki:
    image: grafana/loki:2.3.0
    ports:
      - ${LOKI_DOCKER_COMPOSE_PORT}:3100
    command: -config.file=/etc/loki/local-config.yaml
  tempo:
    image: grafana/tempo:1.1.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - ${TEMPO_DOCKER_COMPOSE_PORT}:8000 # tempo
      - 55681:55681 # otlp http
volumes:
  grafana-data: {}