name: Gyantrade CI/CD

on:
  - push

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Set up Elixir
      uses: erlef/setup-beam@v1.9.4
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]

    - name: Step + Build Cache
      id: mix-cache
      uses: actions/cache@v2
      with:
        path: | 
          deps
          _build
          ~/.mix
        key: ${{ runner.os }}-gameplatform-mix-deps+build-${{ hashFiles('**/mix.lock', '**/mix.exs', '**/config/*') }}
        restore-keys: ${{ runner.os }}-gameplatform-mix-deps+build-${{ hashFiles('**/mix.lock', '**/mix.exs', '**/config/*') }}

    - name: Install Rebar / Hex
      run: |
        mix local.rebar --force
        mix local.hex --force

    - name: Install dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
       git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "git@github.com:" 
       make deps
      env: 
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
        GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}

    - name: "docker Compose setup"
      run: make purge setup_test 

    - name: "Running Unit Test"
      run: |
        mix test

    - name: "Run credo"
      run: | 
        mix credo

    - name: "docker Compose Stop and clean"
      if: always()
      run:  |
        make stop clean 

